name: Publish to PyPI

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  build-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          ref: refs/tags/${{ github.event.release.tag_name }}
          persist-credentials: false
      - uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          python-version: "3.13"
      - run: uv build
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
